[package]
name = "citadel-crud"
version = "0.1.0"
authors = ["Nathaniel Pisarski <nathanpisarski@gmail.com>"]
description = "Create tangible CRUD components for concern separation and dependency injection. Currently only works with SqlLite"
license = "MIT"

[dependencies]
rusqlite = "0.13.0"